- name: Setup MongoDB
  hosts: all
  tasks:
     - name: copy MongoDB repo file
       ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

     - name: Install MongoDB
       ansible.builtin.copy:
        name: mongodb-org
        state: latest

     - name: update mongoDB listen address
       ansible.builtin.replace:
         path: /etc/mongod.conf
         regexp: '127.0.0.1'
         replace: '0.0.0.0'

     - name: start mongoDB service
       ansible.builtin.systemd:
         state: restarted
         name: nginx
         enabled: true






#  echo -e "\e[33mCopy MongoDB Repo file \e[0m"
#  cp /home/centos/roboshop-shell/mongodb.repo /etc/yum.repos.d/mongo.repo &>>/tmp/roboshop.log
#  echo -e "\e[33mInstalling MongoDB Server\e[0m"
#  yum install mongodb-org -y &>>/tmp/roboshop.log
#  echo -e "\e[33mUpdate MongoDB listen address\e[0m"
#  sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
#  echo -e "\e[33mStart MongoDB Service\e[0m"
#  systemctl enable mongod &>>/tmp/roboshop.log
#  systemctl restart mongod &>>/tmp/roboshop.log